# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      
r_packages:
- covr

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

notifications:
  email:
    on_success: change
    on_failure: change
    
env:
  global:
    - _R_CHECK_TIMINGS_="0"
