# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
dist: trusty
cache: packages

r_packages:
- covr

after_success:
  - Rscript -e 'library(covr); codecov()'

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

notifications:
  email:
    on_success: change
    on_failure: change
    
env:
  global:
    - _R_CHECK_TIMINGS_="0"

# From https://github.com/leeper/rio/blob/master/.travis.yml
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX=g++-4.9
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11
